import Link from "next/link";
import { requireUser, getActiveMembership, SCHOOL_NAME } from "@/lib/auth";
import { signOut } from "@/app/auth/actions";
import { redirect } from "next/navigation";

export default async function PendingApprovalPage() {
  const { user, profile, memberships } = await requireUser();
  if (await getActiveMembership()) redirect("/dashboard");
  const membership = memberships[0];
  const unavailable = !membership || membership.status === "active";
  const suspended = membership?.status === "suspended";
  const rejected = membership?.status === "rejected";
  return <main className="min-h-screen bg-[#f6f8f5] px-6 py-10 sm:px-10"><div className="mx-auto flex min-h-[calc(100vh-5rem)] max-w-xl flex-col justify-center"><Link href="/" className="mb-10 flex items-center gap-3 text-sm font-semibold tracking-wide text-[#20584c]"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#20584c] text-lg text-white">K</span>{SCHOOL_NAME}</Link><div className="rounded-[2rem] border border-[#dce7e1] bg-white p-8 shadow-[0_20px_60px_rgba(32,88,76,.08)] sm:p-10"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#e98a6a]">Status akses akun</p><h1 className="mt-3 text-3xl font-semibold tracking-tight text-[#18312c]">{unavailable ? "Akses sekolah belum tersedia" : suspended ? "Akses ditangguhkan" : rejected ? "Pengajuan ditolak" : "Menunggu persetujuan"}</h1><p className="mt-4 leading-7 text-[#60736e]">{unavailable ? "Akun Anda berhasil masuk, tetapi belum memiliki sekolah aktif yang dapat diakses. Hubungi administrator sekolah." : suspended ? `Akses sekolah Anda sedang ditangguhkan. Hubungi administrator ${SCHOOL_NAME}.` : rejected ? `Pengajuan akses sekolah Anda ditolak. Hubungi administrator ${SCHOOL_NAME}.` : `Akun Anda telah terverifikasi, namun masih menunggu persetujuan administrator ${SCHOOL_NAME}.`}</p><dl className="mt-8 divide-y divide-[#e6eee9] rounded-2xl border border-[#e6eee9] px-5"><div className="flex justify-between gap-4 py-4 text-sm"><dt className="text-[#60736e]">Nama</dt><dd className="text-right font-semibold text-[#18312c]">{profile?.full_name ?? "-"}</dd></div><div className="flex justify-between gap-4 py-4 text-sm"><dt className="text-[#60736e]">Email</dt><dd className="max-w-[60%] break-all text-right font-semibold text-[#18312c]">{user.email}</dd></div><div className="flex justify-between gap-4 py-4 text-sm"><dt className="text-[#60736e]">Status</dt><dd className="font-semibold capitalize text-[#b85e43]">{unavailable ? "Belum tersedia" : membership?.status}</dd></div></dl><form action={signOut} className="mt-8"><button type="submit" className="w-full rounded-xl border border-[#cbdcd3] px-4 py-3 text-sm font-semibold text-[#20584c] transition hover:border-[#2f7163]">Keluar</button></form></div></div></main>;
}
